# Generated by Django 3.2.16 on 2023-08-07 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('auth_code', models.CharField(blank=True, max_length=4)),
                ('invite_code', models.CharField(blank=True, max_length=6, unique=True)),
                ('has_used_invite', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('gender', models.CharField(blank=True, choices=[('women', 'женщина'), ('men', 'мужчина')], max_length=10, null=True, verbose_name='Пол')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Администратор')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последний визит')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании')),
                ('full_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('name',),
            },
        ),
    ]
